package org.gradle.wrapper;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.util.Locale;
import java.util.Properties;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Minimal Gradle wrapper implementation so this repository is buildable without bundling
 * the official gradle-wrapper.jar (which is usually generated by Gradle).
 *
 * It reads gradle/wrapper/gradle-wrapper.properties, downloads the Gradle distribution,
 * unzips it into ~/.gradle/wrapper/dists, then invokes the embedded Gradle launcher.
 */
public final class GradleWrapperMain {

    public static void main(String[] args) throws Exception {
        Path projectDir = Paths.get(System.getProperty("user.dir"));
        Path propsPath = projectDir.resolve("gradle").resolve("wrapper").resolve("gradle-wrapper.properties");
        if (!Files.exists(propsPath)) {
            System.err.println("Missing gradle-wrapper.properties at: " + propsPath);
            System.exit(1);
        }

        Properties props = new Properties();
        try (InputStream in = new FileInputStream(propsPath.toFile())) {
            props.load(in);
        }

        String rawUrl = props.getProperty("distributionUrl");
        if (rawUrl == null || rawUrl.trim().isEmpty()) {
            System.err.println("distributionUrl is missing in gradle-wrapper.properties");
            System.exit(1);
        }
        String distributionUrl = unescapeDistributionUrl(rawUrl.trim());

        String gradleUserHome = System.getenv("GRADLE_USER_HOME");
        if (gradleUserHome == null || gradleUserHome.trim().isEmpty()) {
            gradleUserHome = Paths.get(System.getProperty("user.home"), ".gradle").toString();
        }

        String zipFileName = distributionUrl.substring(distributionUrl.lastIndexOf('/') + 1);
        String distName = zipFileName.replaceAll("\\.zip$", "");
        String hash = sha256Short(distributionUrl);

        Path distsBase = Paths.get(gradleUserHome, "wrapper", "dists", distName, hash);
        Files.createDirectories(distsBase);

        Path zipPath = distsBase.resolve(zipFileName);
        if (!Files.exists(zipPath)) {
            download(distributionUrl, zipPath);
        }

        Path gradleHome = findGradleHome(distsBase);
        if (gradleHome == null) {
            unzip(zipPath, distsBase);
            gradleHome = findGradleHome(distsBase);
        }

        if (gradleHome == null) {
            System.err.println("Could not locate extracted Gradle distribution under: " + distsBase);
            System.exit(1);
        }

        boolean isWindows = System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("win");
        Path gradleExec = isWindows
                ? gradleHome.resolve("bin").resolve("gradle.bat")
                : gradleHome.resolve("bin").resolve("gradle");

        if (!Files.exists(gradleExec)) {
            System.err.println("Gradle executable not found: " + gradleExec);
            System.exit(1);
        }

        String[] cmd = new String[args.length + 1];
        cmd[0] = gradleExec.toAbsolutePath().toString();
        System.arraycopy(args, 0, cmd, 1, args.length);

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.directory(projectDir.toFile());
        pb.inheritIO();

        Process p = pb.start();
        int code = p.waitFor();
        System.exit(code);
    }

    private static String unescapeDistributionUrl(String raw) {
        // Typical wrapper properties use: https\://services.gradle.org/...
        // After Properties.load(), it becomes: https\://... or https\://... depending on escaping.
        // Remove backslashes used to escape ':' and '/'.
        return raw.replace("\\:", ":").replace("\\/", "/").replace("\\", "");
    }

    private static void download(String url, Path target) throws IOException {
        System.out.println("Downloading Gradle distribution:");
        System.out.println("  " + url);
        try (InputStream in = new BufferedInputStream(new URL(url).openStream());
             OutputStream out = new BufferedOutputStream(Files.newOutputStream(target))) {
            byte[] buffer = new byte[8192];
            int read;
            long total = 0;
            while ((read = in.read(buffer)) != -1) {
                out.write(buffer, 0, read);
                total += read;
            }
            System.out.println("Downloaded " + total + " bytes to: " + target);
        }
    }

    private static void unzip(Path zipFile, Path destDir) throws IOException {
        System.out.println("Extracting Gradle distribution to: " + destDir);
        try (ZipInputStream zis = new ZipInputStream(new BufferedInputStream(Files.newInputStream(zipFile)))) {
            ZipEntry entry;
            byte[] buffer = new byte[8192];
            while ((entry = zis.getNextEntry()) != null) {
                Path outPath = destDir.resolve(entry.getName()).normalize();
                if (!outPath.startsWith(destDir)) {
                    throw new IOException("Zip entry is outside of target dir: " + entry.getName());
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(outPath);
                } else {
                    Files.createDirectories(outPath.getParent());
                    try (OutputStream out = new BufferedOutputStream(Files.newOutputStream(outPath))) {
                        int read;
                        while ((read = zis.read(buffer)) != -1) {
                            out.write(buffer, 0, read);
                        }
                    }
                    if (outPath.toString().endsWith("/bin/gradle") || outPath.toString().endsWith("\\bin\\gradle")) {
                        outPath.toFile().setExecutable(true, false);
                    }
                }
                zis.closeEntry();
            }
        }
    }

    private static Path findGradleHome(Path distsBase) throws IOException {
        // Gradle zips typically contain a single top-level folder: gradle-x.y
        try (DirectoryStream<Path> ds = Files.newDirectoryStream(distsBase)) {
            for (Path p : ds) {
                if (Files.isDirectory(p) && p.getFileName().toString().startsWith("gradle-")) {
                    return p;
                }
            }
        }
        return null;
    }

    private static String sha256Short(String s) throws Exception {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] digest = md.digest(s.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte b : digest) {
            sb.append(String.format("%02x", b));
        }
        return sb.substring(0, 12);
    }
}
